import csv
from scraper import scrape

top_jobs = [
    "AI Specialist",
    "AR Developer",
    "Account Executive",
    "Aerospace Engineer",
    "Application Support Analyst",
    "Artificial Intelligence Engineer",
    "Automation Engineer",
    "Back-end Developer",
    "Big Data Engineer",
    "Biomedical Engineer",
    "Blockchain Developer",
    "Brand Manager",
    "Business Analyst",
    "Business Development Manager",
    "Business Intelligence Developer",
    "CRM Developer",
    "Chemical Engineer",
    "Civil Engineer",
    "Clinical Psychologist",
    "Cloud Engineer",
    "Cloud Solutions Architect",
    "Cloud Solutions Developer",
    "Computer Forensics Investigator",
    "Computer Hardware Engineer",
    "Computer Network Architect",
    "Computer Programmer",
    "Computer Systems Analyst",
    "Computer and Information Research Scientist",
    "Computer and Information Systems Manager",
    "Content Manager",
    "Counseling Psychologist",
    "Credit Analyst",
    "Cybersecurity Analyst",
    "Data Analyst",
    "Data Center Support Specialist",
    "Data Engineer",
    "Data Scientist",
    "Data Warehouse Architect",
    "Database Administrator",
    "Database Developer",
    "DevOps Engineer",
    "Digital Marketing Manager",
    "Digital Marketing Specialist",
    "ERP Consultant",
    "Electrical Engineer",
    "Embedded Systems Engineer",
    "Embedded Systems Software Developer",
    "Enterprise Architect",
    "Environmental Engineer",
    "Financial Analyst",
    "Financial Planner",
    "Front-end Developer",
    "Full Stack Developer",
    "GIS Specialist",
    "Game Developer",
    "Health IT Specialist",
    "IT Auditor",
    "IT Consultant",
    "IT Director",
    "IT Manager",
    "IT Project Manager",
    "IT Risk Analyst",
    "IT Sales Professional",
    "IT Security Consultant",
    "IT Support Specialist",
    "IT Technician",
    "IT Trainer",
    "Industrial Engineer",
    "Information Security Analyst",
    "Information Security Manager",
    "Integration Specialist",
    "Investment Banker",
    "IoT Developer",
    "Linux System Administrator",
    "Machine Learning Engineer",
    "Market Research Analyst",
    "Marketing Manager",
    "Mechanical Engineer",
    "Mobile App Developer",
    "Mobile Application Architect",
    "Multimedia Artist/Animator",
    "Network Administrator",
    "Network Architect",
    "Network Engineer",
    "Network Security Engineer",
    "Penetration Tester",
    "Petroleum Engineer",
    "Quality Assurance Engineer",
    "Risk Manager",
    "SEO Specialist",
    "Sales Engineer",
    "Sales Manager",
    "Sales Representative",
    "Social Media Manager",
    "Social Media Manager",
    "Software Architect",
    "Software Developer",
    "Software Development Manager",
    "Software Engineer",
    "Software Quality Assurance (QA) Tester",
    "Solution Architect",
    "System Security Administrator",
    "Systems Administrator",
    "Systems Analyst",
    "Systems Analyst",
    "Systems Engineer",
    "Technical Support Specialist",
    "Technical Writer",
    "UI Designer",
    "UI/UX Designer",
    "UX Designer",
    "UX Researcher",
    "VR Developer",
    "Web Developer",
    "Wireless Network Engineer",
]

for job_role in top_jobs:
    jobs = scrape(
        sites=["indeed", "linkedin", "glassdoor"],
        search_term=job_role,
        job_count=100,
    )
    print(f"Found {len(jobs)} jobs for {job_role}")
    print(jobs.head())
    jobs.to_csv(
        f"./data/{job_role}_jobs.csv",
        quoting=csv.QUOTE_NONNUMERIC,
        escapechar="\\",
        index=False,
    )
    print(f"Sucessfully Completed")
